language: perl

perl:
    - "5.19"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
    - "5.8"

before_install:
    - "echo 'user CHIM' > ~/.pause"
    - "cpanm -q -n Test::CPAN::Meta"
    - "cpanm -q -n Test::Pod"

install:
    - "dzil authordeps --missing | xargs cpanm -q -n && dzil listdeps --missing | xargs cpanm -q -n"

script:
    - "dzil test --release"

after_success:
    - "cpanm -q -n Dist::Zilla::App::Command::cover Devel::Cover::Report::Coveralls"
    - "dzil cover -test"
    - "dzil cover -report coveralls"
